#!/bin/sh

# process gnvim flags
# hat tip to http://stackoverflow.com/a/14203146/17597

OPTIND=1         # Reset in case getopts has been used previously in the shell.

# default values
opt_blocking=''

while getopts "f" opt; do
    case "$opt" in
    f)  opt_blocking='-W -n'
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

# launch Neovim.app via open

# touch files if they don't already exist
for i in "$@"; do
    if [ ! -f "$i" ]; then
        # try your best but don't complain
        touch "$i" 2>/dev/null
    fi
done

# pass any CLI params to Neovim before passing option flags
# see https://github.com/rogual/neovim-dot-app/issues/204
open -n -a Neovim "$@" $opt_blocking --args --cwd "$PWD"
